-- Seed de partidos brasileiros (números TSE)
INSERT INTO partido (numero, sigla, nome) VALUES
    (10, 'REPUBLICANOS', 'Republicanos'),
    (11, 'PP', 'Progressistas'),
    (12, 'PDT', 'Partido Democrático Trabalhista'),
    (13, 'PT', 'Partido dos Trabalhadores'),
    (14, 'UNIÃO', 'União Brasil'),
    (15, 'MDB', 'Movimento Democrático Brasileiro'),
    (16, 'PSTU', 'Partido Socialista dos Trabalhadores Unificado'),
    (17, 'PSL', 'Partido Social Liberal'),
    (18, 'REDE', 'Rede Sustentabilidade'),
    (19, 'PODE', 'Podemos'),
    (20, 'PSC', 'Partido Social Cristão'),
    (21, 'PCB', 'Partido Comunista Brasileiro'),
    (22, 'PL', 'Partido Liberal'),
    (23, 'CIDADANIA', 'Cidadania'),
    (25, 'PRD', 'Partido Renovação Democrática'),
    (27, 'DC', 'Democracia Cristã'),
    (28, 'PRTB', 'Partido Renovador Trabalhista Brasileiro'),
    (29, 'PCO', 'Partido da Causa Operária'),
    (30, 'NOVO', 'Partido Novo'),
    (31, 'PHS', 'Partido Humanista da Solidariedade'),
    (33, 'PMN', 'Partido da Mobilização Nacional'),
    (35, 'PMB', 'Partido da Mulher Brasileira'),
    (36, 'PTC', 'Partido Trabalhista Cristão'),
    (40, 'PSB', 'Partido Socialista Brasileiro'),
    (43, 'PV', 'Partido Verde'),
    (44, 'PRP', 'Partido Republicano Progressista'),
    (45, 'PSDB', 'Partido da Social Democracia Brasileira'),
    (50, 'PSOL', 'Partido Socialismo e Liberdade'),
    (51, 'PATRIOTA', 'Patriota'),
    (54, 'PPL', 'Partido Pátria Livre'),
    (55, 'PSD', 'Partido Social Democrático'),
    (65, 'PCdoB', 'Partido Comunista do Brasil'),
    (70, 'AVANTE', 'Avante'),
    (77, 'SOLIDARIEDADE', 'Solidariedade'),
    (80, 'UP', 'Unidade Popular')
ON CONFLICT (numero) DO UPDATE SET sigla = EXCLUDED.sigla, nome = EXCLUDED.nome;
